version: '3'
services:

  website:
    build: ./website
    container_name: website-website-1
    ports:
      - "3030:3000"
    environment:
      - SESSION_SECRET=CF3ADFF027D32DE62ABCD2E403AC3430AE3EA15D6798B79B24CCF40F4EBF8F27881978CF638624A211FBB1D120108A17D9066C5591B2BDCB41BBC61EE54765AD
    command: npm run start
    depends_on:
      - mongodb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

  counter:
    build: ./counter
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis
    command: npm run start
    depends_on:
      - redis

  mongodb:
    image: mongo
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongodb_data:
    driver: local