version: '3'
services:

  mongodb:
    image: mongo
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
      image: redis:alpine3.20
      container_name: redis_cache_server
      ports:
        - "6379:6379"

  web:
    image: nginx:stable
    volumes:
      - ./templates:/etc/nginx/templates
      - /var/www/html:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  mongodb_data:
    driver: local