FROM node:20.11

WORKDIR /app/conteiner1

COPY ./package*.json ./
RUN npm install

COPY ./routes ./routes
COPY ./views ./views
COPY ./public ./public
COPY ./middleware ./middleware
COPY ./logs ./logs

COPY ./server.js ./

CMD ["node","server.js"]