FROM node:20.11-alpine

WORKDIR /app/container1

COPY ./package*.json ./
RUN npm install

COPY ./public ./public
COPY ./routes ./routes
COPY ./views ./views
COPY ./models ./models
COPY ./middleware ./middleware
COPY ./logs ./logs
COPY ./temp ./temp
COPY ./downloads ./downloads
COPY ./database ./database

COPY ./server.js ./

CMD ["node","server.js"]