FROM node:20.11-alpine

WORKDIR /app/container1

COPY ./**.json ./

RUN npm install

COPY ./src ./src
COPY ./public ./public
COPY ./logs ./logs
COPY ./downloads ./downloads
COPY ./views ./views

RUN mkdir -p public/uploads

CMD ["node","src/server.js"]